### ISSUE TITLE
gestion des cadeaux

### ISSUE THREAD

**Issue by Bakemono-san** [ODCG3/waveCloneBack#8]

**Comment by Bakemono-san** [comment]
on definit par default le montant necessaire pour beneficier d'un cadeaux et la limite de cadeaux a recevoir

si l'utilisateur fait un paiement superieur a la limite tu genere un montant aleatoire inferieur a 1000 et tu l'ajoute a son solde

**Comment by AbdouazizDEV** [comment]
Gestion Cadeau

**Comment by AbdouazizDEV** [comment]
Gestion de cadeaux
